const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const os=require('node:os');
let base,server;
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'review-desk-'));
const relative='/';
(async()=>{let browser;try{
server=spawn(process.env.PYTHON||'python3',[path.join(__dirname,'..','server.py'),'--directory',dir,'--bind','127.0.0.1','--port','0'],{stdio:['ignore','pipe','pipe']});
base=await new Promise((resolve,reject)=>{let output='',errors='';const timer=setTimeout(()=>reject(Error('服务启动超时: '+errors)),15000);server.stderr.on('data',b=>errors+=b);server.on('error',e=>{clearTimeout(timer);reject(e)});server.once('exit',code=>{clearTimeout(timer);reject(Error('服务退出 '+code+': '+errors))});server.stdout.on('data',b=>{output+=b;const match=output.match(/Review Desk: (http:\/\/[^\s]+)/);if(match){clearTimeout(timer);resolve(match[1])}})});

fs.writeFileSync(dir+'/old.html','<!doctype html><h1>旧 HTML</h1><p>旧方案仍然可以批注。</p>');fs.utimesSync(dir+'/old.html',1,1);
fs.writeFileSync(dir+'/image.svg','<svg xmlns="http://www.w3.org/2000/svg" width="80" height="20"><rect width="80" height="20" fill="green"/></svg>');
fs.writeFileSync(dir+'/方案.md','# Markdown 验收\n\n这段原文用于批注。\n\n## 能力清单\n\n- [x] 已完成\n- [ ] 待验证\n\n| 功能 | 状态 |\n| --- | --- |\n| 批注 | 支持 |\n\n```js\nconst value = 42;\n```\n\n> 引用说明\n\n~~删除文字~~\n\n![示例](image.svg)\n\n[章节](#能力清单)\n\n<script>window.injected=true</script>');
browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});const p=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'/');await p.locator('.file-row').first().waitFor();let api=await(await p.request.get(base+'/_preview/files')).json();assert(api.every((f,i)=>i===0||api[i-1].modified>=f.modified));assert(api.find(f=>f.name==='方案.md').kind==='Markdown');assert((await p.locator('.file-info a').first().textContent())==='方案.md');
await p.getByRole('button',{name:'Markdown',exact:true}).click();assert(await p.locator('.file-icon').evaluateAll(es=>es.every(e=>e.textContent==='MD')));await p.getByRole('link',{name:'方案.md',exact:true}).click();const f=p.frameLocator('#page');await f.locator('h1').waitFor();assert.equal(await f.locator('table tbody tr').count(),1);assert.equal(await f.locator('input:checked').count(),1);assert.equal(await f.locator('pre code').textContent(),'const value = 42;\n');assert.equal(await f.locator('s').textContent(),'删除文字');assert(await f.locator('img').evaluate(el=>el.complete&&el.naturalWidth===80));assert.equal(await f.locator('body').evaluate(()=>window.injected),undefined);assert.equal(await f.locator('h2').getAttribute('id'),'能力清单');
await f.locator('p').first().evaluate(el=>{let r=document.createRange();r.selectNodeContents(el);getSelection().removeAllRanges();getSelection().addRange(r);document.dispatchEvent(new PointerEvent('pointerup'))});await p.locator('#pick').click();await p.locator('#note').fill('请补充验收证据。');await p.locator('#save').click();await p.locator('#export').click();await p.waitForFunction(()=>document.querySelector('#copyStatus').textContent.length>0);assert((await p.locator('#output').inputValue()).includes('这段原文用于批注。'));await p.locator('#close').click();await p.reload();await p.locator('.card').waitFor();assert.equal(await p.locator('#count').textContent(),'1');await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.goto(base+'/');await p.locator('.file-row').first().waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.setViewportSize({width:1440,height:1000});
fs.writeFileSync(dir+'/new.markdown','# 新文件\n\n自动收录');await p.getByRole('button',{name:/刷新列表/}).click();await p.getByRole('link',{name:'new.markdown',exact:true}).waitFor();assert.equal(await p.locator('.file-info a').first().textContent(),'new.markdown');
const original=await p.request.get(base+relative+'old.html');assert.equal(await original.text(),fs.readFileSync(dir+'/old.html','utf8'));const raw=await p.request.get(base+relative+encodeURIComponent('方案.md')+'?raw=1');assert.equal(await raw.text(),fs.readFileSync(dir+'/方案.md','utf8'));assert.deepEqual(errors,[]);console.log('PASS: Markdown tables/code/tasks/images/anchors, annotations/copy/persistence, descending timestamps, filters, new file discovery, HTML preservation, raw Markdown, mobile layouts, no JS errors');
}finally{if(browser)await browser.close();if(server&&server.exitCode===null){await new Promise(resolve=>{server.once('exit',resolve);server.kill()})}fs.rmSync(dir,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
